[config]
default_to_workspace = false

[env]
HOST = "0.0.0.0"
PORT = 18080

[tasks.compose-build-app]
command = "docker"
args = [
    "compose", "build", "app",
    "--build-arg", "BUILDKIT_INLINE_CACHE=1", "${@}"
]

[tasks.run]
command = "cargo"
args = ["run", "${@}"]

[tasks.run-in-docker]
dependencies = ["compose-build-app"]
command = "docker"
args = ["compose", "up", "-d", "app"]

[tasks.logs]
command = "docker"
args = ["compose", "logs", "${@}"]

[tasks.build]
command = "cargo"
args = ["build", "${@}"]

[tasks.check]
command = "cargo"
args = ["check"]

[tasks.watch]
run_task = [{ name = ["fmt", "clippy", "test"] }]
watch = true

[tasks.fmt]
command = "cargo"
args = ["fmt", "--all", "${@}"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--all", "--all-targets", "${@}"]

[tasks.test]
install_crate = { crate_name = "cargo-nextest", binary = "cargo", test_arg = ["nextest", "--help"] }
command = "cargo"
args = ["nextest", "run", "--workspace", "--status-level", "all", "--test-threads=1"]

[tasks.clippy-ci]
run_task = "clippy"

[tasks.test-ci]
run_task = "test"

[tasks.compose]
command = "docker"
args = ["compose", "${@}"]

[tasks.compose-down]
command = "docker"
args = ["compose", "down"]

[tasks.compose-remove]
command = "docker"
args = ["compose", "down", "-v"]
